# Generated by Django 4.1.2 on 2022-10-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sushi',
            name='price',
            field=models.FloatField(),
        ),
    ]
